local path = "Lonely Hub/Translate Data/vi.json"

local data = [[{
    "Home": "Trang chủ",
    "Input JobId": "Nhập JobId",
    "Spam Join": "Spam tham gia",
    "Join JobId": "Tham gia JobId",
    "Chat with AI": "Trò chuyện với AI",
    "Rejoin Server": "Vào lại server",
    "Hop Server": "Đổi server",
    "Hop Server Less People": "Đổi server ít người",
    "General Farm": "Tổng quan",
    "Sea Event": "Sự kiện biển",
    "Race V4": "Tộc V4",
    "Quest Farm": "Cày nhiệm vụ",
    "Fishing": "Câu cá",
    "Fruit And Raid": "Trái cây và đột kích",
    "Add Stats": "Thêm chỉ số",
    "Travel": "Du lịch",
    "Visual & Combat": "Ảo Ảnh & Chiến đấu",
    "Store": "Cửa hàng",
    "Setting & Misc": "Cài đặt & Linh tinh",
    "Fighting Style": "Phong cách chiến đấu",
    "Select Melee": "Chọn cận chiến",
    "Auto Buy Melee Select": "Tự động mua cận chiến đã chọn",
    "Ability": "Kĩ năng",
    "Buy Buso": "Mua Buso",
    "Buy Geppo": "Mua Geppo",
    "Buy Soru": "Mua Soru",
    "Buy Ken": "Mua Ken",
    "Sword": "Kiếm",
    "Buy Cutlass": "Mua Cutlass",
    "Buy Katana": "Mua Katana",
    "Buy Iron Mace": "Mua chùy sắt",
    "Buy Duel Katana": "Mua song kiếm",
    "Buy Triple Katana": "Mua tam kiếm",
    "Buy Pipe": "Mua ống nước",
    "Buy Dual-Headed Blade": "Mua kiếm hai đầu",
    "Buy Bisento": "Mua Bisento",
    "Buy Soul Cane": "Mua gậy linh hồn",
    "Gun": "Súng",
    "Buy Slingshot": "Mua ná cao su",
    "Buy Musket": "Mua súng hỏa mai",
    "Buy Dual Flintlock": "Mua song hỏa mai",
    "Buy Flintlock": "Mua hỏa mai",
    "Buy Refined Flintlock": "Mua hỏa mai tinh chế",
    "Buy Cannon": "Mua đại bác",
    "Buy Kabucha": "Mua Kabucha",
    "Accessory": "Phụ kiện",
    "Buy Tomoe Ring": "Mua nhẫn Tomoe",
    "Buy Black Cape": "Mua áo choàng đen",
    "Buy Swordsman Hat": "Mua mũ kiếm sĩ",
    "Ectoplasm": "Vật chất kì dị",
    "Buy Bizarre Rifle": "Mua súng trường kỳ lạ",
    "Buy Ghoul Mask": "Mua mặt nạ ma cà rồng",
    "Fragments": "Nguyên thạch",
    "Buy Refund Stats": "Mua hoàn chỉ số",
    "Buy Reroll Race": "Mua thay đổi chủng tộc",
    "Race": "Chủng tộc",
    "Change Ghoul Race": "Đổi sang chủng tộc ma cà rồng",
    "Buy Cyborg Race": "Mua chủng tộc người máy",
    "Craft Items": "Chế tạo vật phẩm",
    "Craft Dragon Heart": "Chế tạo dragon heart",
    "Craft Dragon Storm": "Chế tạo dragon storm",
    "Craft Dino Hood": "Chế tạo mũ khủng long",
    "Craft Shark Tooth": "Chế tạo răng cá mập",
    "Craft Terror Jaw": "Chế tạo terro jaw",
    "Craft Shark Anchor": "Chế tạo mỏ neo cá mập",
    "Craft Leviathan Crown": "Chế tạo vương miện Leviathan",
    "Craft Leviathan Shield": "Chế tạo khiên Leviathan",
    "Craft Leviathan Boat": "Chế tạo thuyền Leviathan",
    "Craft Legendary Scroll": "Chế tạo cuộn huyền thoại",
    "Craft Mythical Scroll": "Chế tạo cuộn thần thoại",
    "Info": "Thông tin",
    "Join Discord": "Tham gia Discord",
    "Copy TikTok": "Sao chép TikTok",
    "Copy Youtube": "Sao chép Youtube",
    "Fishing Config": "Cấu hình câu cá",
    "Select Rod": "Chọn cần câu",
    "Select Bait": "Chọn mồi",
    "Auto Fishing Quest": "Tự động nhiệm vụ câu cá",
    "Auto Fishing": "Tự động câu cá",
    "Save Fishing Position": "Lưu vị trí câu cá",
    "Auto Fish Saved Pos": "Tự động câu ở vị trí đã lưu",
    "Auto Sell Fish": "Tự động bán cá",
    "Auto Slap Battle": "Tự động slap battle",
    "Combat": "Chiến đấu",
    "Select Players": "Chọn người chơi",
    "Refresh Player List": "Làm mới danh sách người chơi",
    "Teleport To Select Players": "Dịch chuyển đến người chơi đã chọn",
    "Aimbot Nearest": "Aimbot kẻ địch gần nhất",
    "No Aim Mobs": "Không nhắm vào quái",
    "Enable Invisible": "Bật tàng hình",
    "Visual Functions": "Chức năng ảo",
    "Select Color": "Chọn màu",
    "Skill Color": "Màu kỹ năng",
    "Fake Level": "Cấp độ ảo",
    "Fake EXP": "EXP ảo",
    "Fake Beli": "Beli ảo",
    "Fake Fragment": "Nguyên thạch ảo",
    "Esp Items": "Esp vật phẩm",
    "Esp Players": "Esp người chơi",
    "Esp Island": "Esp đảo",
    "Esp Fruits": "Esp trái cây",
    "Esp Chests": "Esp rương",
    "Esp Berries": "Esp quả mọng",
    "Esp Flower": "Esp hoa",
    "Esp Legendary Sword Dealers": "Esp người bán kiếm huyền thoại",
    "Esp Aura Colour Dealers": "Esp người bán màu haki",
    "Esp Gear": "Esp bánh răng",
    "Esp Event Island": "Esp đảo sự kiện",
    "Esp Advanced Fruits Dealer": "Esp người bán trái cây đảo bí ẩn",
    "Select Tool": "Chọn công cụ",
    "Farm": "Farm",
    "Auto Farm Level": "Tự động farm cấp độ",
    "Auto Farm Nearest": "Tự động farm quái gần nhất",
    "Boss": "Trùm",
    "Select Boss": "Chọn trùm",
    "Accept Boss Quest": "Chấp nhận nhiệm vụ trùm",
    "Auto Farm Boss": "Tự động farm trùm",
    "Auto Farm All Boss": "Tự động farm tất cả trùm",
    "Dungeon Event": "Sự kiện ngục tối",
    "Teleport Dungeon": "Dịch chuyển ngục tối",
    "Teleport To NPC Dungeon": "Dịch chuyển đến NPC ngục tối",
    "Teleport To Translation Gate 1": "Dịch chuyển đến Cổng 1",
    "Teleport To Translation Gate 2": "Dịch chuyển đến Cổng 2",
    "Teleport To Translation Gate 3": "Dịch chuyển đến Cổng 3",
    "Auto Farm Dungeon": "Tự động farm ngục tối",
    "Dungeon Card": "Thẻ ngục tối",
    "Select Card": "Chọn thẻ",
    "Auto Pick Card": "Tự động chọn thẻ",
    "Chest": "Rương",
    "Auto Chest [Tween]": "Tự động farm rương [Tween]",
    "Tyrant of the Skies": "Bạo chúa bầu trời",
    "Auto Tyrant of the Skies [Fully]": "Tự động Bạo chúa bầu trời [Hoàn toàn]",
    "Main Quests": "Nhiệm vụ chính",
    "Auto Attack Factory": "Tự động tấn công nhà máy",
    "Auto Pirate Raid": "Tự động đột kích hải tặc",
    "Materials Farm": "Farm vật liệu",
    "Select Materials": "Chọn vật liệu",
    "Start Material Farm": "Bắt đầu farm vật liệu",
    "Auto Berry": "Tự động quả mọng",
    "Auto Ectoplasm": "Tự động vật chất kì dị",
    "Auto Citizen Quest": "Tự động nhiệm vụ công dân",
    "Auto Training Dummy": "Tự động training dummy",
    "Auto Bartilo Quest": "Tự động nhiệm vụ Bartilo",
    "Mastery": "Thông thạo",
    "Select Island Farm": "Chọn đảo farm",
    "Health %": "Máu %",
    "Select Tools": "Chọn công cụ",
    "Select Skills": "Chọn kỹ năng",
    "Auto Farm Mastery": "Tự động farm thành thạo",
    "Cake Prince": "Hoàng tử bột",
    "Auto Farm Cake Prince": "Tự động farm hoàng tử bột",
    "Dough King Status:": "Trạng thái vua bột:",
    "Auto Dough King": "Tự động vua bột",
    "Bones": "Xương",
    "Auto Farm Bone": "Tự động farm xương",
    "Auto Soul Reaper [Fully]": "Tự động Thần chết [Đầy đủ]",
    "Auto Random Bones": "Tự động xương ngẫu nhiên",
    "Auto Pray Gravestone": "Tự động cầu nguyện bia mộ",
    "Auto Try Luck": "Tự động thử vận may",
    "Unlocked Chip": "Mở khóa Chip",
    "Auto Unlock Dough Chip": "Tự động mở khóa chip bột",
    "Auto Unlock Phoenix Chip": "Tự động mở khóa chip phượng hoàng",
    "Aura Colours": "Màu hào quang",
    "Teleport Barista Cousin": "Dịch chuyển đến Barista Cousin",
    "Buy Aura Colors": "Mua màu hào quang",
    "Auto Rainbow Colors": "Tự động màu cầu vồng",
    "Accept Rainbow Quest Fast": "Chấp nhận nhiệm vụ cầu vồng nhanh",
    "Observation": "Quan sát",
    "Auto Farm Observation": "Tự động farm haki quan sát",
    "Auto Observation V2": "Tự động quan sát V2",
    "Upgrade Races V2-3": "Nâng cấp chủng tộc V2-3",
    "Auto Race V2": "Tự động chủng tộc V2",
    "Rip_Indra": "Rip_Indra",
    "Auto Attack Rip_indra": "Tự động tấn công Rip_indra",
    "Auto Unlocked Aura Puzzle": "Tự động mở khóa câu đố hào quang",
    "Stop Tween": "Dừng Tween",
    "Pos Y High Distance": "Khoảng cách cao Y",
    "Farm Distance": "Khoảng cách farm",
    "Tween Speed": "Tốc độ Tween",
    "Swap Tool Delay": "Độ trễ đổi công cụ",
    "Max Mob Bring": "Số quái kéo tối đa",
    "Bring Mobs": "Kéo quái",
    "Select UI": "Chọn giao diện",
    "Bypass TP [Beta]": "Bypass TP [Beta]",
    "Fast Attack [Melee & Sword]": "Tấn công nhanh [Cận chiến & Kiếm]",
    "Fast Attack M1 [Blox Fruit]": "Tấn công nhanh M1 [Trái ác quỷ]",
    "Aura M1 [Blox Fruit] - No Eqiup Tool": "Aura M1 [Trái ác quỷ] - Không cần công cụ",
    "Auto Shoot [ Gun ( BETA ) ]": "Tự động bắn [Súng (BETA)]",
    "Auto Translate": "Tự động dịch",
    "Faster Attack [ Beta ]": "Tấn công nhanh hơn [Beta]",
    "Select Tool For Super Fast": "Chọn công cụ cho đánh nhanh",
    "Tween Pos Y High": "Tween vị trí Y cao",
    "Auto Haki": "Tự động Haki",
    "Auto Accept Quests": "Tự động chấp nhận nhiệm vụ",
    "Bypass Quest [ Risk ]": "Bypass nhiệm vụ [Rủi ro]",
    "Take Quest Debounce": "Độ trễ nhận nhiệm vụ",
    "Codes": "Mã code",
    "Redeem all Codes": "Đổi tất cả mã",
    "Team": "Đội",
    "Join Pirate Team": "Tham gia đội Hải tặc",
    "Join Marine Team": "Tham gia đội Hải quân",
    "Auto Active Race V3": "Tự động kích hoạt chủng tộc V3",
    "Auto Active Race V4": "Tự động kích hoạt chủng tộc V4",
    "Select Skill": "Chọn kỹ năng",
    "Use Skill Z": "Sử dụng kỹ năng Z",
    "Use Skill X": "Sử dụng kỹ năng X",
    "Use Skill C": "Sử dụng kỹ năng C",
    "Use Skill V": "Sử dụng kỹ năng V",
    "Use Skill F": "Sử dụng kỹ năng F",
    "Menu": "Menu",
    "Awakenings Expert": "Chuyên gia thức tỉnh",
    "Devil Fruit Shop": "Cửa hàng trái ác quỷ",
    "Advanced Fruit Dealer": "Người bán trái cây nâng cao",
    "Titles": "Danh hiệu",
    "Local-Player": "Người chơi cục bộ",
    "Walk Speed": "Tốc độ di chuyển",
    "Speed Hack": "Hack tốc độ",
    "High Jump": "Nhảy cao",
    "Jump Hack": "Hack nhảy",
    "More FPS": "Thêm FPS",
    "Fast Mode": "Chế độ nhanh",
    "Boost FPS": "Tăng FPS",
    "Others": "Khác",
    "Walk on Water": "Đi trên nước",
    "Anti AFK": "Chống AFK",
    "Auto Set Spawn Point": "Tự động đặt điểm hồi sinh",
    "Safe Mode": "Chế độ an toàn",
    "Screen": "Màn hình",
    "White Screen": "Màn hình trắng",
    "Black Screen": "Màn hình đen",
    "Blur Screen": "Màn hình mờ",
    "Blur Amount": "Lượng mờ",
    "Misc": "Linh tinh",
    "Spin pos when farm": "Xoay vị trí khi farm",
    "Stats": "Chỉ số",
    "Stats Upgrade Delay": "Độ trễ nâng cấp chỉ số",
    "Stats Value": "Giá trị chỉ số",
    "Add Energy": "Thêm Năng lượng",
    "Add Defense": "Thêm Phòng thủ",
    "Add Swords": "Thêm Kiếm",
    "Add Gun": "Thêm Súng",
    "Add Blox Fruit": "Thêm Trái ác quỷ",
    "Next World": "Thế giới tiếp theo",
    "Auto Second Sea": "Tự động biển thứ hai",
    "Auto Third Sea": "Tự động biển thứ ba",
    "Tushita And Yama": "Tushita và Yama",
    "Elites Process": "Quá trình tinh nhuệ",
    "Auto Elite Hunter": "Tự động thợ săn tinh nhuệ",
    "Stop If Have Items": "Dừng nếu có vật phẩm",
    "Auto Tushita": "Tự động Tushita",
    "Auto Yama": "Tự động Yama",
    "Cursed Dual Katana": "Song kiếm nguyền rủa",
    "Auto Cursed Dual Katana (Yama Quest)": "Tự động song kiếm nguyền rủa (Nhiệm vụ Yama)",
    "Auto Cursed Dual Katana (Tushita Quest)": "Tự động song kiếm nguyền rủa (Nhiệm vụ Tushita)",
    "Auto Cursed Dual Katana (Last quest)": "Tự động song kiếm nguyền rủa (Nhiệm vụ cuối)",
    "Auto Dual Cursed Katana": "Tự động song kiếm nguyền rủa",
    "Get & Buy Melee": "Nhận & Mua cận chiến",
    "Get Melee From Inventory": "Lấy cận chiến từ kho đồ",
    "Auto Buy Melee": "Tự động mua cận chiến",
    "True Triple Katana": "Tam kiếm thực sự",
    "Buy Legendary Sword": "Mua kiếm huyền thoại",
    "Buy True Triple Katana Sword": "Mua tam kiếm thực sự",
    "Tween to Legendary Sword Dealer": "Tween đến người bán kiếm huyền thoại",
    "Pole Sword": "Kiếm Pole",
    "Auto Get Pole Sword": "Tự động lấy kiếm Pole",
    "Law Raid": "Đột kích Law",
    "Auto Kill Law": "Tự động giết Law",
    "Buy Microchip Law": "Mua vi mạch Law",
    "Start Law Raids": "Bắt đầu đột kích Law",
    "First Sea Items": "Vật phẩm biển thứ nhất",
    "Auto Saw Sword": "Tự động kiếm Saw",
    "Auto Unlock Saber": "Tự động mở khóa Saber",
    "Auto Cool Glasses": "Tự động kính mát",
    "Auto Usoap's Hat": "Tự động mũ Usoap",
    "Auto Warden Sword": "Tự động kiếm Warden",
    "Auto Marine Coat": "Tự động áo choàng Marine",
    "Auto Swan Coat": "Tự động áo choàng Swan",
    "Rengoku": "Rengoku",
    "Auto Rengoku Sword": "Tự động kiếm Rengoku",
    "Auto Key Rengoku": "Tự động chìa khóa Rengoku",
    "Second Sea Items": "Vật phẩm biển thứ hai",
    "Auto Dragon Trident": "Tự động đinh ba rồng",
    "Auto Long Sword": "Tự động kiếm dài",
    "Auto Black Spikey": "Tự động Black Spikey",
    "Auto Dark Blade V3": "Tự động Dark Blade V3",
    "Auto Midnight Blade": "Tự động kiếm Midnight",
    "Auto Darkbeard": "Tự động Darkbeard",
    "Auto Unlock Don Swan": "Tự động mở khóa Don Swan",
    "Auto Swan Glasses": "Tự động kính Swan",
    "Bosses": "Trùm",
    "Auto Whitebeard": "Tự động Whitebeard",
    "Third Sea Items": "Vật phẩm biển thứ ba",
    "Auto Buddy": "Tự động Buddy",
    "Auto Canvender": "Tự động Canvender",
    "Auto Twin Hooks": "Tự động Twin Hooks",
    "Auto Serpent Bow": "Tự động cung Serpent",
    "Auto Lei Accessory": "Tự động phụ kiện Lei",
    "Mirage": "Ảo ảnh",
    "Auto Mirage Island": "Tự động đảo bí ẩn",
    "Auto Tween To Highest Point": "Tự động Tween đến điểm cao nhất",
    "Auto Look Moon": "Tự động nhìn mặt trăng",
    "Auto Get Gear": "Tự động lấy bánh răng",
    "Easy See": "Dễ nhìn",
    "Auto Tween Advanced Fruit Dealer": "Tự động Tween đến người bán trái cây nâng cao",
    "Auto Collect Mirage Chest": "Tự động thu thập rương đảo bí ẩn",
    "Skull Guitars": "Guitar đầu lâu",
    "Auto Soul Guitar": "Tự động guitar linh hồn",
    "Talk With Stone": "Nói chuyện với Đá",
    "Tiers V4 ": "Bậc V4 ",
    "Auto Pull Lever": "Tự động gạt cần",
    "Auto Train V4": "Tự động huấn luyện V4",
    "Teleport to Temple of Time": "Dịch chuyển đến Đền thời gian",
    "Teleport to Ancient One": "Dịch chuyển đến Ancient One",
    "Teleport to Ancient Clock": "Dịch chuyển đến Đồng hồ cổ",
    "Tween to Race Doors": "Tween đến cửa chủng tộc",
    "Auto Complete Trial": "Tự động hoàn thành thử thách",
    "Auto Kill Player Trial": "Tự động giết người chơi thử thách",
    "Boat Settings": "Cài đặt thuyền",
    "Select Boats": "Chọn thuyền",
    "Buy Boats": "Mua thuyền",
    "Drive Boat Speed": "Tốc độ lái thuyền",
    "Fly Boat": "Thuyền bay",
    "ESP Boat": "ESP thuyền",
    "Dojo": "Võ đường",
    "Auto Dojo Trainer": "Tự động huấn luyện viên võ đường",
    "Auto Dragon Hunter": "Tự động thợ săn rồng",
    "Draco Race": "Chủng tộc Draco",
    "Tween To Upgrade Draco Trial": "Tween để nâng cấp thử thách Draco",
    "Auto Draco V1": "Tự động Draco V1",
    "Auto Draco V2": "Tự động Draco V2",
    "Auto Draco V3": "Tự động Draco V3",
    "Auto Trial Draco": "Tự động thử thách Draco",
    "Auto Train Draco": "Tự động huấn luyện Draco",
    "Change To Draco Race": "Đổi sang chủng tộc Draco",
    "Upgrade Dragon Talon": "Nâng cấp Vuốt rồng",
    "Select Sea Level": "Chọn cấp độ biển",
    "Auto Sea Event": "Tự động sự kiện biển",
    "Use M1 Fruit Sea Event": "Sử dụng M1 trái cây sự kiện biển",
    "Use Dragon Storm Sea Event": "Sử dụng bão rồng sự kiện biển",
    "Drive To Hydra": "Lái đến Hydra",
    "Dodge Skill": "Né kỹ năng",
    "Buy Levi Spy": "Mua Levi Spy",
    "Frozen Dimension:": "Chiều không gian đóng băng:",
    "Tween To Frozen Dimension": "Tween đến chiều không gian đóng băng",
    "Auto Attack Shark": "Tự động tấn công cá mập",
    "Auto Attack Piranha": "Tự động tấn công cá Piranha",
    "Auto Attack Terror Shark": "Tự động tấn công cá mập khủng bố",
    "Auto Attack Fish Crew": "Tự động tấn công thủy thủ cá",
    "Auto Attack Haunted Crew": "Tự động tấn công thủy thủ ma ám",
    "Auto Attack Pirate Brigade": "Tự động tấn công lữ đoàn hải tặc",
    "Auto Attack Fish Boat": "Tự động tấn công thuyền cá",
    "Auto Attack Sea Beast": "Tự động tấn công quái thú biển",
    "Auto Attack Leviathan": "Tự động tấn công Leviathan",
    "Weapon Spam Skill": "Spam kỹ năng vũ khí",
    "Auto Use Melee": "Tự động sử dụng cận chiến",
    "Auto Use Sword": "Tự động sử dụng kiếm",
    "Auto Use Gun": "Tự động sử dụng súng",
    "Auto Use Fruit": "Tự động sử dụng trái cây",
    "Skill Hold Time": "Thời gian giữ kỹ năng",
    "Switch Tool Delay": "Độ trễ đổi công cụ",
    "Kitsune Event": "Sự kiện Kitsune",
    "Auto Kitsune Island": "Tự động đảo Kitsune",
    "Auto Teleport to Shrine Actived": "Tự động dịch chuyển đến đền đã kích hoạt",
    "Auto Trade Azure Ember": "Tự động trao đổi Azure Ember",
    "Auto Collect Azure Ember": "Tự động thu thập Azure Ember",
    "Trade Items Azure": "Trao đổi vật phẩm Azure",
    "Talk with Kitsune statue": "Nói chuyện với tượng Kitsune",
    "Volcanic Magnet": "Nam châm núi lửa",
    "Craft Volcanic Magnet": "Chế tạo nam châm núi lửa",
    "Auto Craft Volcanic Magnet": "Tự động chế tạo nam châm núi lửa",
    "Prehistoric Island": "Đảo tiền sử",
    "Auto Find Prehistoric Island": "Tự động tìm đảo tiền sử",
    "Auto Patch Prehistoric Event": "Tự động dập lửa",
    "Auto Collect Dino Bones": "Tự động thu thập xương khủng long",
    "Auto Collect Dragon Eggs": "Tự động thu thập trứng rồng",
    "Auto Reset When Complete Volcano": "Tự động reset khi hoàn thành núi lửa",
    "NPC Teleport": "Dịch chuyển NPC",
    "Select NPC": "Chọn NPC",
    "Teleport To NPC": "Dịch chuyển đến NPC",
    "Raiding": "Đột kích",
    "Select Chip": "Chọn chip",
    "Buy Chips Beli": "Mua chip bằng Beli",
    "Buy Chips Blox Fruit": "Mua chip bằng Trái ác quỷ",
    "Get Fruit In Inventory Low Beli": "Nhận trái cây trong kho với giá Beli thấp",
    "Auto Start Raid": "Tự động bắt đầu đột kích",
    "Kill Aura": "Kill Aura",
    "Auto Buy Chip Raid": "Tự động mua chip đột kích",
    "Teleport To Lab": "Dịch chuyển đến phòng thí nghiệm",
    "Auto Farm Raid": "Tự động farm đột kích",
    "Auto Awakening": "Tự động thức tỉnh",
    "World": "Thế giới",
    "Teleport Old World": "Dịch chuyển thế giới cũ",
    "Teleport New World": "Dịch chuyển thế giới mới",
    "Teleport Third Sea": "Dịch chuyển biển thứ ba",
    "Island": "Đảo",
    "Select Island": "Chọn đảo",
    "Teleport To Island": "Dịch chuyển đến đảo",
    "Blox Fruits": "Trái ác quỷ",
    "Select Fruit": "Chọn trái cây",
    "Buy Fruit": "Mua trái cây",
    "Mirage Stock": "Kho ảo ảnh",
    "Buy Mirage Stock": "Mua kho ảo ảnh",
    "Auto Random Fruit": "Tự động trái cây ngẫu nhiên",
    "Auto Store Fruit": "Tự động cất trái cây",
    "Auto Tween to Fruit": "Tự động Tween đến trái cây",
    "Auto Teleport Fruit": "Tự động dịch chuyển trái cây",
    "Auto Drop Fruit": "Tự động thả trái cây",
    "Anti Ban": "Chống ban",
    "Hop if admin join": "Nhảy nếu admin vào",
    "Auto Hop (30 Min)": "Tự động nhảy (30 Phút)",
    "Rejoin If Kick": "Vào lại nếu bị kick",
    "Give Kamui": "Nhận Kamui",
    "Give Uzoth Tool (Nuke)": "Nhận công cụ của Uzoth (Nuke)",
    "Rain Fruit Old": "Mưa trái cũ",
    "Rain Fruit New": "Mưa trái mới",
    "Give Divine Art": "Nhận võ thiên thần",
    "Give Celestial Art": "Nhận võ thiên thể",
    "Give Triple Dark Blade": "Nhận tam kiếm yoru",
    "Give Black Blast": "Nhận đường chém đen",
    "Give Black Nuke": "Nhận vụ nổ đen",
    "Give Doors": "Nhận cửa",
    "Give Rogue Fruit": "Nhận trái Rogue",
    "Give tensei": "Nhận tensei",
    "Artificial intelligence": "Trí tuệ nhân tạo",
    "Open AI Gui": "Mở giao diện AI",
    "If you need help, just ask the AI what you need! ": "Nếu bạn cần trợ giúp, hãy hỏi AI những gì bạn cần!"
}]])

if not isfile(path) then
    makefolder("Lonely Hub")
    makefolder("Lonely Hub/Translate Data")
    writefile(path, data)
    print("[Lonely Hub Translate] Created: " .. path)
else
    print("[Lonely Hub Translate] Already exists: " .. path)
end

print("Init Successful!")
